# List of plugins
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
set-option -g default-shell /bin/bash

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

#set -g @resurrect-processes 'ssh nvim'
set -g @resurrect-strategy-nvim 'session'

set -g mouse on
# Don't copy on mouse release; keep the selection highlighted
unbind -T copy-mode    MouseDragEnd1Pane
unbind -T copy-mode-vi MouseDragEnd1Pane

# Clear selection on click
bind -T copy-mode    MouseDown1Pane if -F '#{selection_present}' 'select-pane ; send -X cancel' 'select-pane'
bind -T copy-mode-vi MouseDown1Pane if -F '#{selection_present}' 'select-pane ; send -X cancel' 'select-pane'

# 'c' is copy once text is selected
bind -T copy-mode    c send -X copy-pipe-and-cancel "xclip -selection clipboard -in"
bind -T copy-mode-vi c send -X copy-pipe-and-cancel "xclip -selection clipboard -in"

bind -n WheelUpPane if -F "#{||:#{mouse_any_flag},#{pane_in_mode}}" \
  "send -M" \
  "if -F '#{alternate_on}' 'send-keys -t= Up Up Up' 'copy-mode -e -t='"

bind -n WheelDownPane if -F "#{||:#{mouse_any_flag},#{pane_in_mode}}" \
  "send -M" \
  "if -F '#{alternate_on}' 'send-keys -t= Down Down Down' 'send -M'"

bind k select-pane -U 
bind j select-pane -D 
bind h select-pane -L 
bind l select-pane -R 

set -g set-clipboard on
set -g allow-passthrough on

set-option -s escape-time 0
set-option -g status-interval 5
set-option -g focus-events on
set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '~/.tmux/plugins/tpm/tpm'
